# Generated by Django 3.0.3 on 2020-02-19 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accepted',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name=20)),
                ('scientific_name', models.CharField(max_length=60)),
                ('family', models.CharField(max_length=20)),
                ('genus', models.CharField(max_length=30)),
                ('specific_epiteth', models.CharField(max_length=30)),
                ('infra_epiteth', models.CharField(max_length=30)),
                ('taxon_rank', models.CharField(max_length=20)),
                ('authorship', models.CharField(max_length=30)),
                ('taxon_status', models.CharField(max_length=30)),
                ('name_status', models.CharField(max_length=30)),
                ('search_str', models.CharField(max_length=50)),
                ('threat_status', models.CharField(max_length=3)),
                ('establishment', models.CharField(max_length=15)),
                ('endemism', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Synonym',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name=20)),
                ('scientific_name', models.CharField(max_length=60)),
                ('family', models.CharField(max_length=20)),
                ('genus', models.CharField(max_length=30)),
                ('specific_epiteth', models.CharField(max_length=30)),
                ('infra_epiteth', models.CharField(max_length=30)),
                ('taxon_rank', models.CharField(max_length=20)),
                ('authorship', models.CharField(max_length=30)),
                ('taxon_status', models.CharField(max_length=30)),
                ('name_status', models.CharField(max_length=30)),
                ('search_str', models.CharField(max_length=50)),
                ('threat_status', models.CharField(max_length=3)),
                ('establishment', models.CharField(max_length=15)),
                ('endemism', models.CharField(max_length=15)),
                ('accepted', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Accepted')),
            ],
        ),
    ]
