# Generated by Django 3.0.3 on 2020-02-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accepted',
            name='authorship',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='accepted',
            name='endemism',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='accepted',
            name='establishment',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='accepted',
            name='family',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='accepted',
            name='genus',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='accepted',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='accepted',
            name='infra_epiteth',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='accepted',
            name='name_status',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='accepted',
            name='scientific_name',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='accepted',
            name='search_str',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='accepted',
            name='specific_epiteth',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='accepted',
            name='taxon_rank',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='accepted',
            name='taxon_status',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='accepted',
            name='threat_status',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='synonym',
            name='authorship',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='synonym',
            name='endemism',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='synonym',
            name='establishment',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='synonym',
            name='family',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='synonym',
            name='genus',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='synonym',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='synonym',
            name='infra_epiteth',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='synonym',
            name='name_status',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='synonym',
            name='scientific_name',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='synonym',
            name='search_str',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='synonym',
            name='specific_epiteth',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='synonym',
            name='taxon_rank',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='synonym',
            name='taxon_status',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='synonym',
            name='threat_status',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
