# Generated by Django 3.0.3 on 2020-02-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200224_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accepted',
            name='authorship',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='accepted',
            name='genus',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='accepted',
            name='infra_epiteth',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='accepted',
            name='name_status',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='accepted',
            name='search_str',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='accepted',
            name='specific_epiteth',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='accepted',
            name='taxon_status',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='synonym',
            name='authorship',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='synonym',
            name='genus',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='synonym',
            name='infra_epiteth',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='synonym',
            name='name_status',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='synonym',
            name='search_str',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='synonym',
            name='specific_epiteth',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='synonym',
            name='taxon_status',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
