# Generated by Django 3.0.3 on 2020-02-24 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200224_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accepted',
            name='authorship',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='accepted',
            name='scientific_name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='synonym',
            name='scientific_name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='synonym',
            name='search_str',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
