# Generated by Django 3.0.3 on 2020-02-24 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200224_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accepted',
            name='search_str',
            field=models.CharField(db_index=True, max_length=70, null=True),
        ),
    ]
