# Generated by Django 3.0.3 on 2020-02-24 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200224_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synonym',
            name='authorship',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
