# Generated by Django 3.0.3 on 2020-02-25 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200224_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('scientific_name', models.CharField(max_length=120, null=True)),
                ('family', models.CharField(max_length=20, null=True)),
                ('genus', models.CharField(max_length=60, null=True)),
                ('specific_epiteth', models.CharField(max_length=60, null=True)),
                ('infra_epiteth', models.CharField(max_length=60, null=True)),
                ('taxon_rank', models.CharField(max_length=20, null=True)),
                ('authorship', models.CharField(max_length=120, null=True)),
                ('taxon_status', models.CharField(max_length=60, null=True)),
                ('name_status', models.CharField(max_length=60, null=True)),
                ('threat_status', models.CharField(max_length=12, null=True)),
                ('establishment', models.CharField(max_length=15, null=True)),
                ('endemism', models.CharField(max_length=15, null=True)),
                ('life_form', models.CharField(max_length=70, null=True)),
                ('habitat', models.CharField(max_length=90, null=True)),
                ('vegetation_type', models.CharField(max_length=120, null=True)),
                ('occurrence', models.CharField(max_length=150, null=True)),
                ('domain', models.CharField(max_length=120, null=True)),
                ('accepted', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Names',
            fields=[
                ('search_str', models.CharField(max_length=120, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Relationships',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('synonym_id', models.IntegerField()),
                ('accepted_id', models.IntegerField()),
                ('accepted', models.BooleanField()),
                ('relationship', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShortNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=9)),
            ],
        ),
        migrations.RemoveField(
            model_name='synonym',
            name='accepted',
        ),
        migrations.DeleteModel(
            name='Accepted',
        ),
        migrations.DeleteModel(
            name='Synonym',
        ),
        migrations.AddField(
            model_name='details',
            name='search_str',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Names'),
        ),
        migrations.AddField(
            model_name='details',
            name='short_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ShortNames'),
        ),
    ]
