# Generated by Django 3.0.3 on 2020-02-25 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200225_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortnames',
            name='short_name',
            field=models.CharField(max_length=20),
        ),
    ]
