# Generated by Django 3.0.3 on 2020-02-25 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200225_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='accepted',
        ),
    ]
