# Generated by Django 3.0.3 on 2020-02-25 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200225_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='threat_status',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
