# Generated by Django 3.0.3 on 2020-02-25 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200225_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='habitat',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
