# Generated by Django 3.0.3 on 2020-02-26 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20200226_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationships',
            name='accepted_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted', to='api.Details'),
        ),
        migrations.AlterField(
            model_name='relationships',
            name='synonym_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='synonym', to='api.Details'),
        ),
    ]
